// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'CheckAwsVpc' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:DnsProxy.Console.Program.CheckAwsVpc~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'Task Program.CheckAwsVpc()' passes a literal string as parameter 'message' of a call to 'void LoggerExtensions.LogInformation(ILogger logger, string message, params object[] args)'. Retrieve the following string(s) from a resource table instead: \"No AWS config found!\".", Justification = "<Pending>", Scope = "member", Target = "~M:DnsProxy.Console.Program.CheckAwsVpc~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'CheckForAwsMfaAsync' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:DnsProxy.Console.Program.CheckForAwsMfaAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'void Program.CreateHeader()' passes a literal string as parameter 'value' of a call to 'void Console.WriteLine(string value)'. Retrieve the following string(s) from a resource table instead: \"starts up BLun.de DNS Proxy ...\".", Justification = "<Pending>", Scope = "member", Target = "~M:DnsProxy.Console.Program.CreateHeader")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'Task<int> Program.Main(string[] args)' passes a literal string as parameter 'message' of a call to 'void LoggerExtensions.LogInformation(ILogger logger, string message, params object[] args)'. Retrieve the following string(s) from a resource table instead: \"stop {DefaultTitle}\".", Justification = "<Pending>", Scope = "member", Target = "~M:DnsProxy.Console.Program.Main(System.String[])~System.Threading.Tasks.Task{System.Int32}")]